spring:
  application:
    name: trip-finder
  threads:
    virtual:
      enabled: true

services:
  accommodation-url: http://localhost:7070/sec02/accommodations/
  event-url: http://localhost:7070/sec02/events/
  local-recommendation-url: http://localhost:7070/sec02/local-recommendations/
  transportation-url: http://localhost:7070/sec02/transportation/
  weather-url: http://localhost:7070/sec02/weather/
  flight-search-url: http://localhost:7070/sec03/flight/search/
  flight-reservation-url: http://localhost:7070/sec03/flight/reserve/


resilience4j:
  timelimiter:
    instances:
      weather:
        timeout-duration: 2s

  retry:
    instances:
      events:
        max-attempts: 2
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.client.ResourceAccessException

  circuitbreaker:
    instances:
      recommendations:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
